name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update && sudo apt install nasm -y
    - name: make
      run: sudo make -f GNUmakefile VERBOSE=1 -j$(nproc)

